export interface Country {
  id:   string // ISO 3166-1 alpha-2
  name: string
  code: string // E.164 dial code, with leading +
}

// Regional indicator symbols are U+1F1E6..U+1F1FF, offset from 'A'..'Z' by 127397.
export function flagEmoji(id: string): string {
  return id.toUpperCase().replace(/./g, c => String.fromCodePoint(c.charCodeAt(0) + 127397))
}

// All UN member states + a few common territories, sorted alphabetically by name.
export const COUNTRIES: Country[] = [
  { id: 'AF', name: 'Afghanistan', code: '+93' },
  { id: 'AL', name: 'Albania', code: '+355' },
  { id: 'DZ', name: 'Algeria', code: '+213' },
  { id: 'AD', name: 'Andorra', code: '+376' },
  { id: 'AO', name: 'Angola', code: '+244' },
  { id: 'AG', name: 'Antigua and Barbuda', code: '+1268' },
  { id: 'AR', name: 'Argentina', code: '+54' },
  { id: 'AM', name: 'Armenia', code: '+374' },
  { id: 'AU', name: 'Australia', code: '+61' },
  { id: 'AT', name: 'Austria', code: '+43' },
  { id: 'AZ', name: 'Azerbaijan', code: '+994' },
  { id: 'BS', name: 'Bahamas', code: '+1242' },
  { id: 'BH', name: 'Bahrain', code: '+973' },
  { id: 'BD', name: 'Bangladesh', code: '+880' },
  { id: 'BB', name: 'Barbados', code: '+1246' },
  { id: 'BY', name: 'Belarus', code: '+375' },
  { id: 'BE', name: 'Belgium', code: '+32' },
  { id: 'BZ', name: 'Belize', code: '+501' },
  { id: 'BJ', name: 'Benin', code: '+229' },
  { id: 'BT', name: 'Bhutan', code: '+975' },
  { id: 'BO', name: 'Bolivia', code: '+591' },
  { id: 'BA', name: 'Bosnia and Herzegovina', code: '+387' },
  { id: 'BW', name: 'Botswana', code: '+267' },
  { id: 'BR', name: 'Brazil', code: '+55' },
  { id: 'BN', name: 'Brunei', code: '+673' },
  { id: 'BG', name: 'Bulgaria', code: '+359' },
  { id: 'BF', name: 'Burkina Faso', code: '+226' },
  { id: 'BI', name: 'Burundi', code: '+257' },
  { id: 'CV', name: 'Cabo Verde', code: '+238' },
  { id: 'KH', name: 'Cambodia', code: '+855' },
  { id: 'CM', name: 'Cameroon', code: '+237' },
  { id: 'CA', name: 'Canada', code: '+1' },
  { id: 'CF', name: 'Central African Republic', code: '+236' },
  { id: 'TD', name: 'Chad', code: '+235' },
  { id: 'CL', name: 'Chile', code: '+56' },
  { id: 'CN', name: 'China', code: '+86' },
  { id: 'CO', name: 'Colombia', code: '+57' },
  { id: 'KM', name: 'Comoros', code: '+269' },
  { id: 'CG', name: 'Congo (Congo-Brazzaville)', code: '+242' },
  { id: 'CD', name: 'Congo (DRC)', code: '+243' },
  { id: 'CR', name: 'Costa Rica', code: '+506' },
  { id: 'HR', name: 'Croatia', code: '+385' },
  { id: 'CU', name: 'Cuba', code: '+53' },
  { id: 'CY', name: 'Cyprus', code: '+357' },
  { id: 'CZ', name: 'Czechia', code: '+420' },
  { id: 'DK', name: 'Denmark', code: '+45' },
  { id: 'DJ', name: 'Djibouti', code: '+253' },
  { id: 'DM', name: 'Dominica', code: '+1767' },
  { id: 'DO', name: 'Dominican Republic', code: '+1809' },
  { id: 'EC', name: 'Ecuador', code: '+593' },
  { id: 'EG', name: 'Egypt', code: '+20' },
  { id: 'SV', name: 'El Salvador', code: '+503' },
  { id: 'GQ', name: 'Equatorial Guinea', code: '+240' },
  { id: 'ER', name: 'Eritrea', code: '+291' },
  { id: 'EE', name: 'Estonia', code: '+372' },
  { id: 'SZ', name: 'Eswatini', code: '+268' },
  { id: 'ET', name: 'Ethiopia', code: '+251' },
  { id: 'FJ', name: 'Fiji', code: '+679' },
  { id: 'FI', name: 'Finland', code: '+358' },
  { id: 'FR', name: 'France', code: '+33' },
  { id: 'GA', name: 'Gabon', code: '+241' },
  { id: 'GM', name: 'Gambia', code: '+220' },
  { id: 'GE', name: 'Georgia', code: '+995' },
  { id: 'DE', name: 'Germany', code: '+49' },
  { id: 'GH', name: 'Ghana', code: '+233' },
  { id: 'GR', name: 'Greece', code: '+30' },
  { id: 'GD', name: 'Grenada', code: '+1473' },
  { id: 'GT', name: 'Guatemala', code: '+502' },
  { id: 'GN', name: 'Guinea', code: '+224' },
  { id: 'GW', name: 'Guinea-Bissau', code: '+245' },
  { id: 'GY', name: 'Guyana', code: '+592' },
  { id: 'HT', name: 'Haiti', code: '+509' },
  { id: 'HN', name: 'Honduras', code: '+504' },
  { id: 'HK', name: 'Hong Kong', code: '+852' },
  { id: 'HU', name: 'Hungary', code: '+36' },
  { id: 'IS', name: 'Iceland', code: '+354' },
  { id: 'IN', name: 'India', code: '+91' },
  { id: 'ID', name: 'Indonesia', code: '+62' },
  { id: 'IR', name: 'Iran', code: '+98' },
  { id: 'IQ', name: 'Iraq', code: '+964' },
  { id: 'IE', name: 'Ireland', code: '+353' },
  { id: 'IL', name: 'Israel', code: '+972' },
  { id: 'IT', name: 'Italy', code: '+39' },
  { id: 'JM', name: 'Jamaica', code: '+1876' },
  { id: 'JP', name: 'Japan', code: '+81' },
  { id: 'JO', name: 'Jordan', code: '+962' },
  { id: 'KZ', name: 'Kazakhstan', code: '+7' },
  { id: 'KE', name: 'Kenya', code: '+254' },
  { id: 'KI', name: 'Kiribati', code: '+686' },
  { id: 'XK', name: 'Kosovo', code: '+383' },
  { id: 'KW', name: 'Kuwait', code: '+965' },
  { id: 'KG', name: 'Kyrgyzstan', code: '+996' },
  { id: 'LA', name: 'Laos', code: '+856' },
  { id: 'LV', name: 'Latvia', code: '+371' },
  { id: 'LB', name: 'Lebanon', code: '+961' },
  { id: 'LS', name: 'Lesotho', code: '+266' },
  { id: 'LR', name: 'Liberia', code: '+231' },
  { id: 'LY', name: 'Libya', code: '+218' },
  { id: 'LI', name: 'Liechtenstein', code: '+423' },
  { id: 'LT', name: 'Lithuania', code: '+370' },
  { id: 'LU', name: 'Luxembourg', code: '+352' },
  { id: 'MO', name: 'Macau', code: '+853' },
  { id: 'MG', name: 'Madagascar', code: '+261' },
  { id: 'MW', name: 'Malawi', code: '+265' },
  { id: 'MY', name: 'Malaysia', code: '+60' },
  { id: 'MV', name: 'Maldives', code: '+960' },
  { id: 'ML', name: 'Mali', code: '+223' },
  { id: 'MT', name: 'Malta', code: '+356' },
  { id: 'MH', name: 'Marshall Islands', code: '+692' },
  { id: 'MR', name: 'Mauritania', code: '+222' },
  { id: 'MU', name: 'Mauritius', code: '+230' },
  { id: 'MX', name: 'Mexico', code: '+52' },
  { id: 'FM', name: 'Micronesia', code: '+691' },
  { id: 'MD', name: 'Moldova', code: '+373' },
  { id: 'MC', name: 'Monaco', code: '+377' },
  { id: 'MN', name: 'Mongolia', code: '+976' },
  { id: 'ME', name: 'Montenegro', code: '+382' },
  { id: 'MA', name: 'Morocco', code: '+212' },
  { id: 'MZ', name: 'Mozambique', code: '+258' },
  { id: 'MM', name: 'Myanmar', code: '+95' },
  { id: 'NA', name: 'Namibia', code: '+264' },
  { id: 'NR', name: 'Nauru', code: '+674' },
  { id: 'NP', name: 'Nepal', code: '+977' },
  { id: 'NL', name: 'Netherlands', code: '+31' },
  { id: 'NZ', name: 'New Zealand', code: '+64' },
  { id: 'NI', name: 'Nicaragua', code: '+505' },
  { id: 'NE', name: 'Niger', code: '+227' },
  { id: 'NG', name: 'Nigeria', code: '+234' },
  { id: 'KP', name: 'North Korea', code: '+850' },
  { id: 'MK', name: 'North Macedonia', code: '+389' },
  { id: 'NO', name: 'Norway', code: '+47' },
  { id: 'OM', name: 'Oman', code: '+968' },
  { id: 'PK', name: 'Pakistan', code: '+92' },
  { id: 'PW', name: 'Palau', code: '+680' },
  { id: 'PS', name: 'Palestine', code: '+970' },
  { id: 'PA', name: 'Panama', code: '+507' },
  { id: 'PG', name: 'Papua New Guinea', code: '+675' },
  { id: 'PY', name: 'Paraguay', code: '+595' },
  { id: 'PE', name: 'Peru', code: '+51' },
  { id: 'PH', name: 'Philippines', code: '+63' },
  { id: 'PL', name: 'Poland', code: '+48' },
  { id: 'PT', name: 'Portugal', code: '+351' },
  { id: 'QA', name: 'Qatar', code: '+974' },
  { id: 'RO', name: 'Romania', code: '+40' },
  { id: 'RU', name: 'Russia', code: '+7' },
  { id: 'RW', name: 'Rwanda', code: '+250' },
  { id: 'KN', name: 'Saint Kitts and Nevis', code: '+1869' },
  { id: 'LC', name: 'Saint Lucia', code: '+1758' },
  { id: 'VC', name: 'Saint Vincent and the Grenadines', code: '+1784' },
  { id: 'WS', name: 'Samoa', code: '+685' },
  { id: 'SM', name: 'San Marino', code: '+378' },
  { id: 'ST', name: 'Sao Tome and Principe', code: '+239' },
  { id: 'SA', name: 'Saudi Arabia', code: '+966' },
  { id: 'SN', name: 'Senegal', code: '+221' },
  { id: 'RS', name: 'Serbia', code: '+381' },
  { id: 'SC', name: 'Seychelles', code: '+248' },
  { id: 'SL', name: 'Sierra Leone', code: '+232' },
  { id: 'SG', name: 'Singapore', code: '+65' },
  { id: 'SK', name: 'Slovakia', code: '+421' },
  { id: 'SI', name: 'Slovenia', code: '+386' },
  { id: 'SB', name: 'Solomon Islands', code: '+677' },
  { id: 'SO', name: 'Somalia', code: '+252' },
  { id: 'ZA', name: 'South Africa', code: '+27' },
  { id: 'KR', name: 'South Korea', code: '+82' },
  { id: 'SS', name: 'South Sudan', code: '+211' },
  { id: 'ES', name: 'Spain', code: '+34' },
  { id: 'LK', name: 'Sri Lanka', code: '+94' },
  { id: 'SD', name: 'Sudan', code: '+249' },
  { id: 'SR', name: 'Suriname', code: '+597' },
  { id: 'SE', name: 'Sweden', code: '+46' },
  { id: 'CH', name: 'Switzerland', code: '+41' },
  { id: 'SY', name: 'Syria', code: '+963' },
  { id: 'TW', name: 'Taiwan', code: '+886' },
  { id: 'TJ', name: 'Tajikistan', code: '+992' },
  { id: 'TZ', name: 'Tanzania', code: '+255' },
  { id: 'TH', name: 'Thailand', code: '+66' },
  { id: 'TL', name: 'Timor-Leste', code: '+670' },
  { id: 'TG', name: 'Togo', code: '+228' },
  { id: 'TO', name: 'Tonga', code: '+676' },
  { id: 'TT', name: 'Trinidad and Tobago', code: '+1868' },
  { id: 'TN', name: 'Tunisia', code: '+216' },
  { id: 'TR', name: 'Turkey', code: '+90' },
  { id: 'TM', name: 'Turkmenistan', code: '+993' },
  { id: 'TV', name: 'Tuvalu', code: '+688' },
  { id: 'UG', name: 'Uganda', code: '+256' },
  { id: 'UA', name: 'Ukraine', code: '+380' },
  { id: 'AE', name: 'United Arab Emirates', code: '+971' },
  { id: 'GB', name: 'United Kingdom', code: '+44' },
  { id: 'US', name: 'United States', code: '+1' },
  { id: 'UY', name: 'Uruguay', code: '+598' },
  { id: 'UZ', name: 'Uzbekistan', code: '+998' },
  { id: 'VU', name: 'Vanuatu', code: '+678' },
  { id: 'VA', name: 'Vatican City', code: '+379' },
  { id: 'VE', name: 'Venezuela', code: '+58' },
  { id: 'VN', name: 'Vietnam', code: '+84' },
  { id: 'YE', name: 'Yemen', code: '+967' },
  { id: 'ZM', name: 'Zambia', code: '+260' },
  { id: 'ZW', name: 'Zimbabwe', code: '+263' },
]

export const DEFAULT_COUNTRY: Country = COUNTRIES.find(c => c.id === 'LK')!
